### ISSUE TITLE
Deal -1 Cards for Armor Penalty

### ISSUE THREAD

**Issue by Seferan** [Sebaestschjin/gloomhaven-saveloader#29]
Would be cool if the system could be smart enough to deal out -1 cards if you have armor like Hide Armor or Chainmail.   
- Would need to take into account any "perks" which allow you to ignore negative item effects (Berserker has this)
- Since people may not equip the armor for each mission, maybe want to just put the -1 cards on top of the Armor orthogonally and let the player put them in their modifier deck.

**Comment by Sebaestschjin** [comment]
Yeah, that would be cool. The perk information already has the flags for
ignoring negative item effects, so that would be easy to do. I think it one
could put the items in the deck automatically when the item is equipped
(which can be determined from its position).
However, one thing that currently hinders me to do that, are the spoilers.
:-) I don't want to look through all items to see which items add how many
negative cards.

Seferan <notifications@github.com> schrieb am So., 28. Juni 2020, 16:31:
